name: Update Progressbar

on:
  push:
    branches: master

jobs:
  update:
    runs-on: ubuntu-latest
    container: bluexleoxgreen/make-progress:latest
    steps:
    - uses: actions/checkout@v1
    - name: update progress bar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./update_progress.sh
