name: Update Progressbar

on: [push]

jobs:
  update:
    branches:
      - master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 -m pip install numpy matplotlib
        ./update_progress.sh
