name: Update Progressbar

on:
  push:
    branches: master

jobs:
  update:
    runs-on: ubuntu-latest
    docker:
      - image: bluexleoxgreen/make-progress
    steps:
    - uses: actions/checkout@v1
    - name: update progress bar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 -m pip install numpy matplotlib
        ./update_progress.sh
